<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyVersion>1.0.1.0</AssemblyVersion>
    <FileVersion>1.0.1.0</FileVersion>
    <Version>1.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Implements.Module.Logger\Implements.Module.Logger.csproj" />
  </ItemGroup>

</Project>
