<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ApplicationIcon />
    <StartupObject />
    <Version>0.0.6</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Murcex.Implements.Configuration" Version="1.0.0" />
    <PackageReference Include="Murcex.KirokuG2" Version="1.0.0" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
  </ItemGroup>

</Project>
