
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <Version>1.0.1</Version>
    <PackageId>Murcex.Configurator</PackageId>
    <Description>Azure Function Configuration Utility Client</Description>
    <Company>Murcex</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Murcex.Implements.Configuration" Version="1.0.1" />
    <PackageReference Include="System.Text.Json" Version="8.0.0" />
  </ItemGroup>

</Project>
