<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <ApplicationIcon />
    <StartupObject />
    <Version>1.0.0</Version>
    <PackageId>Murcex.Configurator</PackageId>
    <Description>Azure Function Configuration Utility Client</Description>
    <Title>Murcex Configurator</Title>
    <Company>Murcex</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Murcex.Implements.Configuration" Version="1.0.0" />
  </ItemGroup>

</Project>
