; --- kquery ---

[kquery]
kquery-url=<url>
kquery-token=<token>

; --- vyudro ---

[site]
pages=signin,login,query-log,view-log
images=function

[page-manager]
type=function

[session-manager]
type=function
default=testpassword

[elements]
background.jpg="https://<your-storage-account-name>.blob.core.windows.net/<container-name>/background.jpg"
signin.png="https://<your-storage-account-name>.blob.core.windows.net/<container-name>/signin.png"
search.png="https://<your-storage-account-name>.blob.core.windows.net/<container-name>/search.png"

[signin]
file=signin.html
security=none

[login]
file=login.html
security=login

[query-log]
file=query-log.html
security=token

[view-log]
file=view-log.html
security=token