<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>1.0.1</Version>
    <PackageId>Murcex.Implements.Configuration</PackageId>
    <Description>Configuration Serialize and Deserialize Utility</Description>
    <Title>Murcex Implements Configuration</Title>
    <Company>Murcex</Company>
  </PropertyGroup>

</Project>
