<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Murcex.Implements.Configuration" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlyQor.Module.Client\PlyQor.Module.Client.csproj" />
    <ProjectReference Include="..\PlyQor.Internal.Engine\PlyQor.Internal.Engine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config.ini">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
