<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Murcex.Implements.DataTools" Version="0.0.1" />
    <PackageReference Include="Murcex.KirokuG2" Version="1.0.0" />
    <PackageReference Include="Murcex.PlyQor.Client" Version="1.0.0" />
    <PackageReference Include="Murcex.Vyudro.Client" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Murcex.PlyQor.Internal.Container\Murcex.PlyQor.Internal.Container.csproj" />
  </ItemGroup>

</Project>
